kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller
spec:
  replicas: 1
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: dit4c/dit4c-container-zeppelin
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m