apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: spark-master
  name: spark-master  
spec:
  replicas: 1
  selector:
    name: spark-master
  template:
    metadata:
      labels:
        name: spark-master
    spec:
      containers:
      - image: gcr.io/caci-main/spark-master:latest
        name: spark-master
        env:
        - name: SPARK_DAEMON_MEMORY
          value: 30g   
        volumeMounts:
          - mountPath: /test-ssd
            name: test-ssd      
        ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
        - containerPort: 7077
          hostPort: 7077
          protocol: TCP
        - containerPort: 9000
          hostPort: 9000
          protocol: TCP
        - containerPort: 50070
          hostPort: 50070
          protocol: TCP
      volumes:
      - name: test-ssd 
        # This GCE PD must already exist.
        hostPath:
          path: /mnt/disks/ssd0
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"    