apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: spark-worker
  name: spark-worker  
spec:
  replicas: 5
  selector:
    name: spark-worker
  template:
    metadata:
      labels:
        name: spark-worker
    spec:
      containers:
      - image: gcr.io/caci-main/spark-worker:latest
        name: spark-worker
        resources:
          requests:                    
            cpu: 400m
            memory: 20Gi
          limits:
            cpu: 500m
            memory: 22Gi
        volumeMounts:
          - mountPath: /root/hdfs/datanode
            name: ssd0        
        env:
        - name: SPARK_WORKER_MEMORY
          value: 20g                               
        ports:
        - containerPort: 7078
          hostPort: 7078
          protocol: TCP
        - containerPort: 50010
          hostPort: 50010
          protocol: TCP
        - containerPort: 50020
          hostPort: 50020
          protocol: TCP
      volumes:
      - name: ssd0 
        # This GCE PD must already exist.
        hostPath:
          path: /mnt/disks/ssd0
      nodeSelector:
        cloud.google.com/gke-local-ssd: "true"        