kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller
spec:
  replicas: 1
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: gcr.io/caci-main/zeppelin:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 400m                                   
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 2Gi