kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller
spec:
  replicas: 1
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: gcr.io/caci-main/zeppelin:latest
          ports:
            - containerPort: 8080
          resources:
            requests:   
              cpu: "3000"                 
              memory: 20Gi
            limits:
              cpu: "3600"
              memory: 24Gi